---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: leafex-cms
spec:
  replicas: 5
  selector:
    matchLabels:
      app: leafex-cms-app
      version: blue
  template:
    metadata:
      name: leafex-cms-pod
      labels:
        app: leafex-cms-app
        version: blue
    spec:
      containers:
      - name: leafex-cms-container
        image: sehlor/CMS:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: leafex-cms-svc
  labels:
    app: leafex-cms-app
spec:
  selector:
    app: leafex-cms-app
    version: blue
  type: NodePort
  ports:
    port: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: leafex-cms-virtualhost
spec:
  rules:
  - host: leafex.co
    http:
      paths:
      - backend:
          serviceName: leafex-cms-svc
          servicePort: 80
