---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: leafex-web-frontend-frontend
spec:
  selector:
    matchLabels:
      app: leafex-web-frontend-app
      version: "1"
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: leafex-web-frontend-app
        version: "1"
    spec:
      containers:
        - name: leafex-web-frontend-app
          image: sehlor/cms:latest
          resources:
            requests:
              memory: "1Mi"
              cpu: "1m"
            limits:
              memory: "2024Mi"
              cpu: "2000m" 
---
apiVersion: v1
kind: Service
metadata:
  name: leafex-web-frontend-svc
spec:
  selector:
    app: leafex-web-frontend-app
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80
  type: NodePort
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: leafex-cms-virtualhost
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: leafex.co
    http:
      paths:
      - path: /
        backend:
          serviceName: leafex-web-frontend-svc
          servicePort: 80